language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

script:
  - make check

notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify